//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegasScriptHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class DefaultBinName : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefaultBinName defaultInstance = ((DefaultBinName)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefaultBinName())));
        
        public static DefaultBinName Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ボイロ音声")]
        public string voiroVoice {
            get {
                return ((string)(this["voiroVoice"]));
            }
            set {
                this["voiroVoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ボイロ字幕")]
        public string voiroJimaku {
            get {
                return ((string)(this["voiroJimaku"]));
            }
            set {
                this["voiroJimaku"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("字幕背景")]
        public string jimakuBackground {
            get {
                return ((string)(this["jimakuBackground"]));
            }
            set {
                this["jimakuBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("立ち絵")]
        public string tachie {
            get {
                return ((string)(this["tachie"]));
            }
            set {
                this["tachie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DL音声")]
        public string dlAudio {
            get {
                return ((string)(this["dlAudio"]));
            }
            set {
                this["dlAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("作成音声")]
        public string createdAudio {
            get {
                return ((string)(this["createdAudio"]));
            }
            set {
                this["createdAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DL動画")]
        public string dlMovie {
            get {
                return ((string)(this["dlMovie"]));
            }
            set {
                this["dlMovie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("作成動画")]
        public string createdMovie {
            get {
                return ((string)(this["createdMovie"]));
            }
            set {
                this["createdMovie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DL画像")]
        public string dlImage {
            get {
                return ((string)(this["dlImage"]));
            }
            set {
                this["dlImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("作成画像")]
        public string createdImage {
            get {
                return ((string)(this["createdImage"]));
            }
            set {
                this["createdImage"] = value;
            }
        }
    }
}
