//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegasScriptHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    public sealed partial class Vegas : global::System.Configuration.ApplicationSettingsBase {
        
        private static Vegas defaultInstance = ((Vegas)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Vegas())));
        
        public static Vegas Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public float AudioInsertInterval {
            get {
                return ((float)(this["AudioInsertInterval"]));
            }
            set {
                this["AudioInsertInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioFileFolder {
            get {
                return ((string)(this["AudioFileFolder"]));
            }
            set {
                this["AudioFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAudioFolderRecursive {
            get {
                return ((bool)(this["IsAudioFolderRecursive"]));
            }
            set {
                this["IsAudioFolderRecursive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsInsertFromStartPosition {
            get {
                return ((bool)(this["IsInsertFromStartPosition"]));
            }
            set {
                this["IsInsertFromStartPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("セリフ")]
        public string AudioTrackName {
            get {
                return ((string)(this["AudioTrackName"]));
            }
            set {
                this["AudioTrackName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double JimakuOutlineWidth {
            get {
                return ((double)(this["JimakuOutlineWidth"]));
            }
            set {
                this["JimakuOutlineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExpandVideoEventMargin {
            get {
                return ((double)(this["ExpandVideoEventMargin"]));
            }
            set {
                this["ExpandVideoEventMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color JimakuColor {
            get {
                return ((global::System.Drawing.Color)(this["JimakuColor"]));
            }
            set {
                this["JimakuColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color JimakuOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["JimakuOutlineColor"]));
            }
            set {
                this["JimakuOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JimakuFilePath {
            get {
                return ((string)(this["JimakuFilePath"]));
            }
            set {
                this["JimakuFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ActorColor {
            get {
                return ((global::System.Drawing.Color)(this["ActorColor"]));
            }
            set {
                this["ActorColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ActorOutlineColor {
            get {
                return ((global::System.Drawing.Color)(this["ActorOutlineColor"]));
            }
            set {
                this["ActorOutlineColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ActorOutlineWidth {
            get {
                return ((double)(this["ActorOutlineWidth"]));
            }
            set {
                this["ActorOutlineWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PrefixBehavior {
            get {
                return ((int)(this["PrefixBehavior"]));
            }
            set {
                this["PrefixBehavior"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseJimakuColorSetting {
            get {
                return ((bool)(this["UseJimakuColorSetting"]));
            }
            set {
                this["UseJimakuColorSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseActorColorSetting {
            get {
                return ((bool)(this["UseActorColorSetting"]));
            }
            set {
                this["UseActorColorSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAudioMediaBin {
            get {
                return ((bool)(this["UseAudioMediaBin"]));
            }
            set {
                this["UseAudioMediaBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseJimakuMediaBin {
            get {
                return ((bool)(this["UseJimakuMediaBin"]));
            }
            set {
                this["UseJimakuMediaBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseActorMediaBin {
            get {
                return ((bool)(this["UseActorMediaBin"]));
            }
            set {
                this["UseActorMediaBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseJimakuBGMediaBin {
            get {
                return ((bool)(this["UseJimakuBGMediaBin"]));
            }
            set {
                this["UseJimakuBGMediaBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseActorBGMediaBin {
            get {
                return ((bool)(this["UseActorBGMediaBin"]));
            }
            set {
                this["UseActorBGMediaBin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ボイロ音声")]
        public string AudioMediaBinName {
            get {
                return ((string)(this["AudioMediaBinName"]));
            }
            set {
                this["AudioMediaBinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ボイロ字幕")]
        public string JimakuMediaBinName {
            get {
                return ((string)(this["JimakuMediaBinName"]));
            }
            set {
                this["JimakuMediaBinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ボイロ声優名")]
        public string ActorMediaBinName {
            get {
                return ((string)(this["ActorMediaBinName"]));
            }
            set {
                this["ActorMediaBinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("字幕背景")]
        public string JimakuBGMediaBinName {
            get {
                return ((string)(this["JimakuBGMediaBinName"]));
            }
            set {
                this["JimakuBGMediaBinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("声優名背景")]
        public string ActorBGMediaBinName {
            get {
                return ((string)(this["ActorBGMediaBinName"]));
            }
            set {
                this["ActorBGMediaBinName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateOneEventCheck {
            get {
                return ((bool)(this["CreateOneEventCheck"]));
            }
            set {
                this["CreateOneEventCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CreateJimakuBG {
            get {
                return ((bool)(this["CreateJimakuBG"]));
            }
            set {
                this["CreateJimakuBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateActorBG {
            get {
                return ((bool)(this["CreateActorBG"]));
            }
            set {
                this["CreateActorBG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("字幕")]
        public string JimakuTrackName {
            get {
                return ((string)(this["JimakuTrackName"]));
            }
            set {
                this["JimakuTrackName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JimakuPresetName {
            get {
                return ((string)(this["JimakuPresetName"]));
            }
            set {
                this["JimakuPresetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActorPresetName {
            get {
                return ((string)(this["ActorPresetName"]));
            }
            set {
                this["ActorPresetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JimakuBGMediaName {
            get {
                return ((string)(this["JimakuBGMediaName"]));
            }
            set {
                this["JimakuBGMediaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActorBGMediaName {
            get {
                return ((string)(this["ActorBGMediaName"]));
            }
            set {
                this["ActorBGMediaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double JimakuBGMargin {
            get {
                return ((double)(this["JimakuBGMargin"]));
            }
            set {
                this["JimakuBGMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ActorBGMargin {
            get {
                return ((double)(this["ActorBGMargin"]));
            }
            set {
                this["ActorBGMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGroupSerifuJimakuEvent {
            get {
                return ((bool)(this["IsGroupSerifuJimakuEvent"]));
            }
            set {
                this["IsGroupSerifuJimakuEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double JimakuMargin {
            get {
                return ((double)(this["JimakuMargin"]));
            }
            set {
                this["JimakuMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ActorMargin {
            get {
                return ((double)(this["ActorMargin"]));
            }
            set {
                this["ActorMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("声優名")]
        public string ActorTrackName {
            get {
                return ((string)(this["ActorTrackName"]));
            }
            set {
                this["ActorTrackName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("字幕背景")]
        public string JimakuBGTrackName {
            get {
                return ((string)(this["JimakuBGTrackName"]));
            }
            set {
                this["JimakuBGTrackName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("声優名背景")]
        public string ActorBGTrackName {
            get {
                return ((string)(this["ActorBGTrackName"]));
            }
            set {
                this["ActorBGTrackName"] = value;
            }
        }
    }
}
