//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VegasScriptHelper.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    public sealed partial class VoiceActorOutlineColor : global::System.Configuration.ApplicationSettingsBase
    {

        private static VoiceActorOutlineColor defaultInstance = ((VoiceActorOutlineColor)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VoiceActorOutlineColor())));

        public static VoiceActorOutlineColor Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ずんだもん
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ずんだもん"]));
            }
            set
            {
                this["ずんだもん"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 波音リツ
        {
            get
            {
                return ((global::System.Drawing.Color)(this["波音リツ"]));
            }
            set
            {
                this["波音リツ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 琴葉_茜
        {
            get
            {
                return ((global::System.Drawing.Color)(this["琴葉_茜"]));
            }
            set
            {
                this["琴葉_茜"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 四国めたん
        {
            get
            {
                return ((global::System.Drawing.Color)(this["四国めたん"]));
            }
            set
            {
                this["四国めたん"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 四国めたん_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["四国めたん_ノーマル_"]));
            }
            set
            {
                this["四国めたん_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 四国めたん_あまあま_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["四国めたん_あまあま_"]));
            }
            set
            {
                this["四国めたん_あまあま_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 四国めたん_ツンツン_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["四国めたん_ツンツン_"]));
            }
            set
            {
                this["四国めたん_ツンツン_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 四国めたん_セクシー_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["四国めたん_セクシー_"]));
            }
            set
            {
                this["四国めたん_セクシー_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 四国めたん_ささやき_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["四国めたん_ささやき_"]));
            }
            set
            {
                this["四国めたん_ささやき_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 四国めたん_ヒソヒソ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["四国めたん_ヒソヒソ_"]));
            }
            set
            {
                this["四国めたん_ヒソヒソ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ずんだもん_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ずんだもん_ノーマル_"]));
            }
            set
            {
                this["ずんだもん_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ずんだもん_あまあま_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ずんだもん_あまあま_"]));
            }
            set
            {
                this["ずんだもん_あまあま_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ずんだもん_ツンツン_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ずんだもん_ツンツン_"]));
            }
            set
            {
                this["ずんだもん_ツンツン_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ずんだもん_セクシー_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ずんだもん_セクシー_"]));
            }
            set
            {
                this["ずんだもん_セクシー_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ずんだもん_ささやき_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ずんだもん_ささやき_"]));
            }
            set
            {
                this["ずんだもん_ささやき_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ずんだもん_ヒソヒソ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ずんだもん_ヒソヒソ_"]));
            }
            set
            {
                this["ずんだもん_ヒソヒソ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 春日部つむぎ
        {
            get
            {
                return ((global::System.Drawing.Color)(this["春日部つむぎ"]));
            }
            set
            {
                this["春日部つむぎ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 雨晴はう
        {
            get
            {
                return ((global::System.Drawing.Color)(this["雨晴はう"]));
            }
            set
            {
                this["雨晴はう"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 玄野武宏
        {
            get
            {
                return ((global::System.Drawing.Color)(this["玄野武宏"]));
            }
            set
            {
                this["玄野武宏"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 玄野武宏_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["玄野武宏_ノーマル_"]));
            }
            set
            {
                this["玄野武宏_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 玄野武宏_喜び_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["玄野武宏_喜び_"]));
            }
            set
            {
                this["玄野武宏_喜び_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 玄野武宏_ツンギレ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["玄野武宏_ツンギレ_"]));
            }
            set
            {
                this["玄野武宏_ツンギレ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 玄野武宏_悲しみ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["玄野武宏_悲しみ_"]));
            }
            set
            {
                this["玄野武宏_悲しみ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 白上虎太郎
        {
            get
            {
                return ((global::System.Drawing.Color)(this["白上虎太郎"]));
            }
            set
            {
                this["白上虎太郎"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 白上虎太郎_ふつう_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["白上虎太郎_ふつう_"]));
            }
            set
            {
                this["白上虎太郎_ふつう_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 白上虎太郎_わーい_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["白上虎太郎_わーい_"]));
            }
            set
            {
                this["白上虎太郎_わーい_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 白上虎太郎_びくびく_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["白上虎太郎_びくびく_"]));
            }
            set
            {
                this["白上虎太郎_びくびく_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 白上虎太郎_おこ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["白上虎太郎_おこ_"]));
            }
            set
            {
                this["白上虎太郎_おこ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 白上虎太郎_ぴえーん_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["白上虎太郎_ぴえーん_"]));
            }
            set
            {
                this["白上虎太郎_ぴえーん_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 青山龍星
        {
            get
            {
                return ((global::System.Drawing.Color)(this["青山龍星"]));
            }
            set
            {
                this["青山龍星"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 冥鳴ひまり
        {
            get
            {
                return ((global::System.Drawing.Color)(this["冥鳴ひまり"]));
            }
            set
            {
                this["冥鳴ひまり"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 九州そら
        {
            get
            {
                return ((global::System.Drawing.Color)(this["九州そら"]));
            }
            set
            {
                this["九州そら"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 九州そら_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["九州そら_ノーマル_"]));
            }
            set
            {
                this["九州そら_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 九州そら_あまあま_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["九州そら_あまあま_"]));
            }
            set
            {
                this["九州そら_あまあま_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 九州そら_ツンツン_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["九州そら_ツンツン_"]));
            }
            set
            {
                this["九州そら_ツンツン_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 九州そら_セクシー_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["九州そら_セクシー_"]));
            }
            set
            {
                this["九州そら_セクシー_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 九州そら_ささやき_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["九州そら_ささやき_"]));
            }
            set
            {
                this["九州そら_ささやき_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 九州そら_ヒソヒソ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["九州そら_ヒソヒソ_"]));
            }
            set
            {
                this["九州そら_ヒソヒソ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color もち子さん
        {
            get
            {
                return ((global::System.Drawing.Color)(this["もち子さん"]));
            }
            set
            {
                this["もち子さん"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 剣崎雌雄
        {
            get
            {
                return ((global::System.Drawing.Color)(this["剣崎雌雄"]));
            }
            set
            {
                this["剣崎雌雄"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WhiteCUL
        {
            get
            {
                return ((global::System.Drawing.Color)(this["WhiteCUL"]));
            }
            set
            {
                this["WhiteCUL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WhiteCUL_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["WhiteCUL_ノーマル_"]));
            }
            set
            {
                this["WhiteCUL_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WhiteCUL_たのしい_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["WhiteCUL_たのしい_"]));
            }
            set
            {
                this["WhiteCUL_たのしい_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WhiteCUL_かなしい_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["WhiteCUL_かなしい_"]));
            }
            set
            {
                this["WhiteCUL_かなしい_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color WhiteCUL_ぴえーん_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["WhiteCUL_ぴえーん_"]));
            }
            set
            {
                this["WhiteCUL_ぴえーん_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 後鬼
        {
            get
            {
                return ((global::System.Drawing.Color)(this["後鬼"]));
            }
            set
            {
                this["後鬼"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 後鬼_人間ver__
        {
            get
            {
                return ((global::System.Drawing.Color)(this["後鬼_人間ver__"]));
            }
            set
            {
                this["後鬼_人間ver__"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 後鬼_ぬいぐるみver__
        {
            get
            {
                return ((global::System.Drawing.Color)(this["後鬼_ぬいぐるみver__"]));
            }
            set
            {
                this["後鬼_ぬいぐるみver__"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color No_7
        {
            get
            {
                return ((global::System.Drawing.Color)(this["No_7"]));
            }
            set
            {
                this["No_7"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color No_7_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["No_7_ノーマル_"]));
            }
            set
            {
                this["No_7_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color No_7_アナウンス_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["No_7_アナウンス_"]));
            }
            set
            {
                this["No_7_アナウンス_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color No_7_読み聞かせ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["No_7_読み聞かせ_"]));
            }
            set
            {
                this["No_7_読み聞かせ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ちび式じい
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ちび式じい"]));
            }
            set
            {
                this["ちび式じい"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 櫻歌ミコ
        {
            get
            {
                return ((global::System.Drawing.Color)(this["櫻歌ミコ"]));
            }
            set
            {
                this["櫻歌ミコ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 櫻歌ミコ_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["櫻歌ミコ_ノーマル_"]));
            }
            set
            {
                this["櫻歌ミコ_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 櫻歌ミコ_第二形態_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["櫻歌ミコ_第二形態_"]));
            }
            set
            {
                this["櫻歌ミコ_第二形態_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 櫻歌ミコ_ロリ_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["櫻歌ミコ_ロリ_"]));
            }
            set
            {
                this["櫻歌ミコ_ロリ_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 小夜_SAYO
        {
            get
            {
                return ((global::System.Drawing.Color)(this["小夜_SAYO"]));
            }
            set
            {
                this["小夜_SAYO"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ナースロボ＿タイプＴ
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ナースロボ＿タイプＴ"]));
            }
            set
            {
                this["ナースロボ＿タイプＴ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ナースロボ＿タイプＴ_ノーマル_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ナースロボ＿タイプＴ_ノーマル_"]));
            }
            set
            {
                this["ナースロボ＿タイプＴ_ノーマル_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ナースロボ＿タイプＴ_楽々_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ナースロボ＿タイプＴ_楽々_"]));
            }
            set
            {
                this["ナースロボ＿タイプＴ_楽々_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ナースロボ＿タイプＴ_恐怖_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ナースロボ＿タイプＴ_恐怖_"]));
            }
            set
            {
                this["ナースロボ＿タイプＴ_恐怖_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ナースロボ＿タイプＴ_内緒話_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ナースロボ＿タイプＴ_内緒話_"]));
            }
            set
            {
                this["ナースロボ＿タイプＴ_内緒話_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 琴葉_葵
        {
            get
            {
                return ((global::System.Drawing.Color)(this["琴葉_葵"]));
            }
            set
            {
                this["琴葉_葵"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 結月ゆかり
        {
            get
            {
                return ((global::System.Drawing.Color)(this["結月ゆかり"]));
            }
            set
            {
                this["結月ゆかり"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 紲星あかり
        {
            get
            {
                return ((global::System.Drawing.Color)(this["紲星あかり"]));
            }
            set
            {
                this["紲星あかり"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 桜乃そら
        {
            get
            {
                return ((global::System.Drawing.Color)(this["桜乃そら"]));
            }
            set
            {
                this["桜乃そら"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 京町セイカ_v1_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["京町セイカ_v1_"]));
            }
            set
            {
                this["京町セイカ_v1_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color フリモメン
        {
            get
            {
                return ((global::System.Drawing.Color)(this["フリモメン"]));
            }
            set
            {
                this["フリモメン"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 東北ずん子
        {
            get
            {
                return ((global::System.Drawing.Color)(this["東北ずん子"]));
            }
            set
            {
                this["東北ずん子"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 女性1
        {
            get
            {
                return ((global::System.Drawing.Color)(this["女性1"]));
            }
            set
            {
                this["女性1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 女性2
        {
            get
            {
                return ((global::System.Drawing.Color)(this["女性2"]));
            }
            set
            {
                this["女性2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 女性3
        {
            get
            {
                return ((global::System.Drawing.Color)(this["女性3"]));
            }
            set
            {
                this["女性3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 女の子
        {
            get
            {
                return ((global::System.Drawing.Color)(this["女の子"]));
            }
            set
            {
                this["女の子"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 男性1
        {
            get
            {
                return ((global::System.Drawing.Color)(this["男性1"]));
            }
            set
            {
                this["男性1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 男性2
        {
            get
            {
                return ((global::System.Drawing.Color)(this["男性2"]));
            }
            set
            {
                this["男性2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 男性3
        {
            get
            {
                return ((global::System.Drawing.Color)(this["男性3"]));
            }
            set
            {
                this["男性3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color さとうささら
        {
            get
            {
                return ((global::System.Drawing.Color)(this["さとうささら"]));
            }
            set
            {
                this["さとうささら"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 小春六花
        {
            get
            {
                return ((global::System.Drawing.Color)(this["小春六花"]));
            }
            set
            {
                this["小春六花"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ロサ_ROSA_
        {
            get
            {
                return ((global::System.Drawing.Color)(this["ロサ_ROSA_"]));
            }
            set
            {
                this["ロサ_ROSA_"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 男性4
        {
            get
            {
                return ((global::System.Drawing.Color)(this["男性4"]));
            }
            set
            {
                this["男性4"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 女声4
        {
            get
            {
                return ((global::System.Drawing.Color)(this["女声4"]));
            }
            set
            {
                this["女声4"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 男の子
        {
            get
            {
                return ((global::System.Drawing.Color)(this["男の子"]));
            }
            set
            {
                this["男の子"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color 彩澄しゅお
        {
            get
            {
                return ((global::System.Drawing.Color)(this["彩澄しゅお"]));
            }
            set
            {
                this["彩澄しゅお"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color 彩澄りりせ
        {
            get
            {
                return ((global::System.Drawing.Color)(this["彩澄りりせ"]));
            }
            set
            {
                this["彩澄りりせ"] = value;
            }
        }
    }
}
